hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

reward_model:
  reward_manager: collabllm

trainer:
  project_name: verl-collabllm

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang
    multi_turn:
      enable: True
      collabllm_rollouts: True
      num_repeat_rollouts: 2
      max_user_turns: 1


