# Target class for this configuration
_target_: verl.workers.config.VeOmniOptimizerConfig

optimizer: adamw

# Learning rate
lr: 1e-3

# LR warmup steps ratio
lr_warmup_ratio: 0.0

# Total training steps
total_training_steps: -1

# Weight decay
weight_decay: 0.01

# Clip gradient
max_grad_norm: 1.0

# LR scheduler type: "constant" or "cosine"
lr_scheduler_type: cosine
